[file name]: _config.yml
[file content begin]
title: "Geometry Dash Demon List"
description: "Неофициальный рейтинг самых сложных уровней в Geometry Dash"
baseurl: ""
url: ""
theme: null

include:
  - data

exclude:
  - .github
  - generate-pages.yml
  - generate-demon-pages.py

# Отключаем Jekyll обработку для статических файлов
defaults:
  - scope:
      path: "data"
      type: "pages"
    values:
      layout: null
      permalink: null

# Отключаем Jekyll полностью для GitHub Pages
plugins: []
[file content end]
