name: Generate Demon Pages

on:
  push:
    paths:
      - 'data/demons.json'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Generate demon pages
      run: |
        python generate-demon-pages.py
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add demon-*.html
        git diff --staged --quiet || git commit -m "Auto-generate demon pages"
        git push
